Metrics/LineLength:
  Max: 99

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - spec/support/*
    - db/**/*
    - config/**/*
    - bin/**/*
    - Gemfile

Metrics/BlockLength:
  Exclude:
    - spec/**/*
